import re
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text

from app.database import get_db
from app.crud import dataset as dataset_crud
from app.api.deps import get_optional_current_user
from app.models.user import User


def _validate_table_name(table_name: str) -> bool:
    """Validate table name to prevent SQL injection."""
    return bool(re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', table_name))


def _get_tile_cors_headers() -> dict[str, str]:
    return {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Max-Age": "86400",
    }


router = APIRouter(prefix="/datasets", tags=["tiles"])


@router.options("/{dataset_id}/tiles/{z}/{x}/{y}.pbf")
async def tiles_options(dataset_id: UUID, z: int, x: int, y: int):
    """Handle CORS preflight requests for tile endpoint."""
    return Response(status_code=204, headers=_get_tile_cors_headers())


@router.get("/{dataset_id}/tiles/{z}/{x}/{y}.pbf")
async def get_vector_tile(
    dataset_id: UUID,
    z: int,
    x: int,
    y: int,
    db: AsyncSession = Depends(get_db),
    current_user: User | None = Depends(get_optional_current_user),
):
    """Serve Mapbox Vector Tiles generated by PostGIS ST_AsMVT."""

    # Validate tile coordinates
    if z < 0 or z > 22:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Zoom level must be between 0 and 22",
        )
    max_coord = (1 << z) - 1
    if x < 0 or x > max_coord or y < 0 or y > max_coord:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Tile coordinates out of range for zoom {z}",
        )

    # Fetch dataset
    dataset = await dataset_crud.get_dataset(db, dataset_id)
    if not dataset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Dataset not found",
        )

    # Access control: public datasets open to all, others require auth
    if not dataset.is_public and not current_user:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Authentication required for non-public datasets",
        )

    if dataset.data_type != "vector":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Tile endpoint only available for vector datasets",
        )

    if not dataset.table_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Dataset has no associated data table",
        )

    table_name = dataset.table_name
    if not _validate_table_name(table_name):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Invalid table name in dataset",
        )

    query = text(f"""
        SELECT ST_AsMVT(tile, 'default', 4096, 'mvt_geom') AS mvt
        FROM (
            SELECT id, properties,
                ST_AsMVTGeom(
                    ST_Transform(geom, 3857),
                    ST_TileEnvelope(:z, :x, :y),
                    4096, 64, true
                ) AS mvt_geom
            FROM "{table_name}"
            WHERE geom IS NOT NULL
              AND ST_Intersects(
                  geom,
                  ST_Transform(ST_TileEnvelope(:z, :x, :y, margin => (64.0 / 4096)), 4326)
              )
        ) AS tile
        WHERE mvt_geom IS NOT NULL
    """)

    result = await db.execute(query, {"z": z, "x": x, "y": y})
    row = result.fetchone()

    mvt_data = row[0] if row else None

    headers = _get_tile_cors_headers()
    headers["Cache-Control"] = "public, max-age=300"

    # Empty tile → 204
    if not mvt_data or len(bytes(mvt_data)) == 0:
        return Response(status_code=204, headers=headers)

    return Response(
        content=bytes(mvt_data),
        media_type="application/x-protobuf",
        headers=headers,
    )
